# config_kiss.yaml

# NOTE: Please note that this is just an example of the advanced configuration for the KISS-ICP
# pipeline and it's not really meant to use for any particular dataset, is just to expose other
# options that are disabled by default

/kiss_icp_node:
  ros__parameters:
    ####    /!\ If you set these ROS-related parameters in the file, they will overwrite the corresponding launch arguments   ####

    base_frame: ""
    lidar_odom_frame: "hesai_lidar"
    publish_odom_tf: False
    invert_odom_tf: False
    position_covariance: 0.1
    orientation_covariance: 0.1

    publish_debug_clouds: True
    use_sim_time: True

    ####    Core KISS-ICP parameters    ####

    data:
      deskew: False
      max_range: 80.0
      min_range: 0.0

    mapping:
      voxel_size: 0.50 # <- optional, default = max_range / 100.0
      max_points_per_voxel: 10

    adaptive_threshold:
      initial_threshold: 2.0
      min_motion_th: 0.1

    registration:
      max_num_iterations: 300 # <- optional
      convergence_criterion: 0.001 # <- optional
      max_num_threads: 0 # <- optional, 0 means automatic